# Multiple Linear Regression

## Importing the libraries

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [5]:
#  importing the data set
dataset = pd.read_csv("50_Startups.csv")
# seperating the dependent and independent variables
x = dataset.iloc[ : , :-1].values
y = dataset.iloc[: , -1].values
# print(x)

In [6]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

## Encoding categorical data

In [7]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.compose import ColumnTransformer # importing the ColumnTransformer class
from sklearn.preprocessing import OneHotEncoder # importing the OneHotEncoder class
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough') # creating an instance of the ColumnTransformer class
x = np.array(ct.fit_transform(x)) # applyin

In [8]:
print(x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

## Splitting the dataset into the Training set and Test set

In [9]:
# tesplit function for splitinf the data into test and training sets
from sklearn.model_selection import train_test_split
# split the data sets into training and testing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

## Training the Multiple Linear Regression model on the Training set

In [10]:
# import the Linear Regression class
from sklearn.linear_model import LinearRegression
# create the linear regression object
regressor = LinearRegression()
# train our object with the dataset 
regressor.fit(x_train, y_train) 

LinearRegression()

## Predicting the Test set results

In [11]:
#  predict the response of the test set based on our trained moddel
y_predict = regressor.predict(x_test)
# convert all numerical values in 2 decimal places with numpy
np.set_printoptions(precision=2)
# creat a numpy concatenation of the two arrays
print(np.concatenate((y_test.reshape(len(y_test),1), y_predict.reshape(len(y_predict),1)),1))


[[103282.38 103015.2 ]
 [144259.4  132582.28]
 [146121.95 132447.74]
 [ 77798.83  71976.1 ]
 [191050.39 178537.48]
 [105008.31 116161.24]
 [ 81229.06  67851.69]
 [ 97483.56  98791.73]
 [110352.25 113969.44]
 [166187.94 167921.07]]


In [12]:
# create a dataframe to view our prediction and the actual array in the test set
prediction_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_predict})
prediction_df

Actual      Predicted
0  103282.38  103015.201598
1  144259.40  132582.277608
2  146121.95  132447.738452
3   77798.83   71976.098513
4  191050.39  178537.482211
5  105008.31  116161.242302
6   81229.06   67851.692097
7   97483.56   98791.733747
8  110352.25  113969.435330
9  166187.94  167921.065696